#pragma once
#include <string>
#include <vector>

namespace ear {
  namespace reference {

    /// Features used by a DirectSpeakers reference case.
    enum DirectSpeakersFeature : unsigned {
      DS_CARTESIAN = 1u,
      DS_SCREEN_EDGE_LOCK = 32u,
      DS_WIDE_SCREEN_SPEAKERS = 64u,
    };

    /// One DirectSpeakers block format rendered by the reference
    /// implementation.
    struct DirectSpeakersCase {
      std::string name;
      /// BS.2051 layout name, or "<name>:SC=<az>" (see layoutForSpec)
      std::string layout;
      unsigned features;
      std::vector<std::string> speakerLabels;
      bool cartesian;
      /// azimuth, elevation, distance (polar) or X, Y, Z (cartesian)
      double position[3];
      bool hasMin[3];
      double minimum[3];
      bool hasMax[3];
      double maximum[3];
      /// "" or "left"/"right" and "top"/"bottom"
      std::string screenEdgeLockHorizontal;
      std::string screenEdgeLockVertical;
      /// channel frequency element with lowPass=120 (LFE)
      bool lfeFreq;
      /// audioPackFormatID of a common definitions pack, or ""
      std::string packFormat;
      std::vector<double> gains;
    };

    /// All cases, generated by
    /// tools/reference/generate_direct_speakers_reference.py
    const std::vector<DirectSpeakersCase>& directSpeakersCases();

  }  // namespace reference
}  // namespace ear
