#pragma once
#include <string>
#include <vector>
#include "ear/layout.hpp"

namespace ear {
  namespace reference {

    /// Features used by a reference case; libear tests expect a
    /// not_implemented exception for cases using features it does not
    /// support yet, and compare gains otherwise.
    enum Feature : unsigned {
      CARTESIAN = 1u,
      CHANNEL_LOCK = 2u,
      DIVERGENCE = 4u,
      ZONE_EXCLUSION = 8u,
      SCREEN_REF = 16u,
      SCREEN_EDGE_LOCK = 32u,
      /// layout spec "<name>:SC=<az>": M+SC/M-SC moved to +-az degrees
      WIDE_SCREEN_SPEAKERS = 64u,
    };

    struct Zone {
      bool cartesian;
      /// polar: minAzimuth, maxAzimuth, minElevation, maxElevation, 0, 0
      /// cartesian: minX, maxX, minY, maxY, minZ, maxZ
      double values[6];
    };

    /// One block format rendered by the reference implementation.
    struct ObjectsCase {
      std::string name;
      /// BS.2051 layout name, or "<name>:SC=<az>" (see layoutForSpec)
      std::string layout;
      unsigned features;
      bool cartesian;
      /// azimuth, elevation, distance (polar) or X, Y, Z (cartesian)
      double position[3];
      double width;
      double height;
      double depth;
      double gain;
      double diffuse;
      bool channelLock;
      /// < 0: no maxDistance
      double channelLockMaxDistance;
      double divergence;
      /// < 0: default range
      double divergenceRange;
      /// divergence given as positionRange (true) or azimuthRange (false)
      bool divergenceCartesian;
      std::vector<Zone> zones;
      bool screenRef;
      /// "" or "left"/"right" and "top"/"bottom"
      std::string screenEdgeLockHorizontal;
      std::string screenEdgeLockVertical;
      /// true if width, height or depth are non-zero (looser tolerance)
      bool usesExtent;
      std::vector<double> direct;
      std::vector<double> diffuseGains;
    };

    /// All cases, generated by tools/reference/generate_objects_reference.py
    const std::vector<ObjectsCase>& objectsCases();

    /// A layout from a case's layout spec: a BS.2051 name, optionally with
    /// ":SC=<az>" moving the M+SC/M-SC loudspeakers to +-az degrees
    Layout layoutForSpec(const std::string& spec);

  }  // namespace reference
}  // namespace ear
